#!/bin/bash
set -euo pipefail

cd -- "$(dirname -- "$0")"
if [[ -d cdmx-bayesopt/.git ]]; then
    git -C cdmx-bayesopt pull --ff-only
else
    git clone https://github.com/the-matter-lab/cdmx-bayesopt.git cdmx-bayesopt
fi
